# .github/workflows/cd.yml
name: CD - 持续部署 (构建并推送 Docker 镜像)

on:
  push:
    branches:
      - main # 只有合并到 main 才触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      # --- (这是新增的！) ---
      - name: 创建生产 .env 文件
        run: |
          echo "DAGSHUB_TRACKING_URI=${{ secrets.DAGSHUB_TRACKING_URI }}" >> .env
          echo "DAGSHUB_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> .env
          echo "DAGSHUB_PASSWORD=${{ secrets.DAGSHUB_PASSWORD }}" >> .env
      # --- (新增结束) ---

      - name: 登录到 GitHub 集装箱仓库 (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
