name: CD - 持续部署 (构建并推送 Docker 镜像)

on:
  push:
    branches:
      - main # 只有合并到 main 才触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 需要写入 GitHub Packages 的权限

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 获取数据 (用于 Docker 构建)
        run: |
          pip install pandas requests scikit-learn
          python get_data.py

      - name: 登录到 GitHub 集装箱仓库 (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest