# .github/workflows/ci.yml

name: CI - 持续集成测试
on:
  pull_request:
    branches:
      - dev
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    env:
      DAGSHUB_TRACKING_URI: ${{ secrets.DAGSHUB_TRACKING_URI }}
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_PASSWORD: ${{ secrets.DAGSHUB_PASSWORD }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[azure] # (包名无所谓)

      - name: 配置 DVC (使用 DagsHub 存储)
        run: |
          # --- (这是最终的修复！) ---
          # 1. 使用 *正确* 的仓库名 'mlops-house-price-predictor'
          dvc remote add origin https://dagshub.com/yamheng/mlops-house-price-predictor.dvc

          # 2. (不变) 设置凭证
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_PASSWORD }}

          # 3. (不变) 设置默认
          dvc remote default origin

      - name: DVC 拉取数据 (用于 Pytest)
        run: |
          # (不变) dvc pull 现在会从正确的遥控器拉取
          dvc pull data/housing.csv.dvc -f

      - name: 运行 Linting (Flake8)
        run: |
          flake8 . --count --show-source --statistics

      - name: 运行单元测试 (Pytest)
        run: |
          pytest

      - name: 获取数据 (用于训练)
        run: python ml/get_data.py

      - name: 运行模型训练 (推送到 DagsHub)
        run: python ml/train.py